server:
  port: 8050

spring:
  cloud:
    gateway:
      #discovery:
        #locator:
          #enabled: true #默认为false需要配置routes，开启则使用默认的路由规则，自动根据 serviceId 创建路由
      routes:
      - id: a #我们自定义的路由 ID，保持唯一
        uri: lb://PRODUCT-DATA-SERVICE
        predicates:
        - Path=/a/** #路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
        filters:
        - StripPrefix=1 # 表示在转发时去掉
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

            #globalcors:
          #cors-configurations:
            #'[/**]':
            #allowedOrigins: "*"
            #allowedMethods:
          #  - GET
  application:
    name: cloud-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



